name: Build and deploy to docker hub

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/next_ds_visualizer:latest

      - name: Deploy to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/next_ds_visualizer:latest

      - name: Verify Pushed Image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/next_ds_visualizer:latest  
      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker pull raghav1205/next_ds_visualizer:latest
            sudo docker stop web-app || true
            sudo docker rm web-app || true
            sudo docker run -d --name web-app -p 3000:3000 \ 
             -e DATABASE_URL=${{secrets.DATABASE_URL}} \
            raghav1205/next_ds_visualizer:latest

